//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by launcher.rc
//
#define IDC_BTN_SETTING                 3
#define IDCANCEL2                       3
#define IDC_BTN_MIN                     5
#define IDD_LAUNCHER_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_DLG_LOGIN                   130
#define IDD_DLG_CONFIG                  131
#define IDD_DLG_TEST                    134
#define IDD_DLG_OTP                     135
#define IDI_INFO                        136
#define IDI_CONFIG                      137
#define IDD_DLG_PORTLIST                138
#define IDI_POLICY                      140
#define IDI_REFRESH                     141
#define IDD_DLG_TIMEOUT                 142
#define IDB_PNG_BG                      145
#define IDB_PNG_LOGO                    146
#define IDB_PNG_BTN                     147
#define IDB_PNG_UNCHK                   148
#define IDB_PNG_CHK                     149
#define IDB_BITMAP1                     151
#define IDB_PNG_EXIT                    156
#define IDB_PNG1                        157
#define IDB_PNG_MIN                     157
#define IDB_PNG_BTN_DOWN                158
#define IDB_PNG_BTN_RUN                 159
#define IDB_PNG_BTN_TURN                160
#define IDB_PNG2                        161
#define IDB_PNG_EYE                     161
#define IDB_PNG_REFRESH                 162
#define IDB_PNG_BTN_INFO                163
#define IDB_PNG3                        164
#define IDB_PNG_STOP                    164
#define IDB_PNG_BTN_SETTING             165
#define IDB_PNG_DISCONN                 166
#define IDB_BMP_DISCON                  167
#define IDB_BMP_CONN                    168
#define IDD_DIALOG1                     169
#define IDD_DLG_64                      169
#define IDC_EDIT1                       1000
#define IDC_EDT_USERNAME                1000
#define IDC_EDIT2                       1001
#define IDC_LST_ITEM                    1001
#define IDC_EDT_PASSWORD                1001
#define IDC_BTN_DOWN                    1002
#define IDC_EDT_MACHINE                 1002
#define IDC_BTN_START                   1003
#define IDC_EDT_SERVER                  1003
#define IDC_BTN_STOP                    1004
#define IDC_EDT_PORT                    1004
#define IDC_BTN_EXIT                    1005
#define IDC_BTN_INFO                    1006
#define IDC_BUTTON1                     1007
#define IDC_EDT_NUM1                    1008
#define IDC_EDT_NUM2                    1009
#define IDC_EDT_NUM3                    1010
#define IDC_LST_PORT                    1010
#define IDC_EDT_NUM4                    1011
#define IDC_BTN_REFRESH                 1011
#define IDC_EDT_NUM5                    1012
#define IDC_STC_STATUS                  1012
#define IDC_EDT_NUM6                    1013
#define IDC_STC_MESSAGE                 1013
#define IDC_CHK_SAVEUSER                1014
#define IDC_STC_ICON                    1017
#define IDC_STC_MID                     1021
#define IDC_STC_MAIL                    1022
#define IDC_STC_PWD                     1023
#define IDC_STC_TITLE                   1024
#define IDC_STC_CLICK                   1025
#define IDC_GRP_MACHINE                 1026
#define IDC_GRP_EMAIL                   1027
#define IDC_GRP_PWD                     1028
#define IDC_STC_GRP_BG                  1029
#define IDC_GRP_IP                      1030
#define IDC_STC_IP                      1031
#define IDC_GRP_PORT                    1032
#define IDC_STC_TITLE2                  1032
#define IDC_STC_SUBTITLE                1032
#define IDC_STC_PORT                    1033
#define IDC_GRP_EMAIL2                  1033
#define IDC_GRP_SERVER                  1033
#define IDC_GRP_OTP                     1034
#define IDC_STC_OTP                     1035
#define IDC_STC_SUBTITLE2               1035
#define IDC_STC_RESEND                  1036
#define IDC_COMBO1                      1037
#define IDC_CMB_IP                      1037
#define IDC_GRP_BG                      1038
#define IDC_GRP_PANEL                   1039
#define IDC_STC_OS                      1040
#define IDC_GRP_PANEL2                  1041
#define IDC_BTN_BACK                    1041
#define IDC_STC_DESC                    1042
#define IDC_BTN_EYE                     1042
#define IDC_GRP_PANEL3                  1043
#define IDC_EDT_XPATH                   1043
#define IDC_PGS_DOWN                    1044
#define IDC_STC_SIZE                    1045
#define IDC_STC_SIZE2                   1046
#define IDC_STC_STATE                   1046
#define IDC_STC_PATH                    1047
#define IDC_STC_DOWN                    1048
#define IDC_STC_DISCON                  1050
#define IDC_STC_DISCON2                 1051
#define IDC_STC_CONN                    1051

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
