//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by KLauncher.rc
//
#define IDOK2                           3
#define IDC_BTN_SUSPEND3                4
#define IDC_BTN_CANCEL3                 5
#define IDC_BTN_STOP3                   6
#define IDD_KLAUNCHER_DIALOG            102
#define IDD_KLAUNCHER_DIALOG_LAUNCHER   103
#define IDR_MAINFRAME                   128
#define IDB_PNG_BG                      132
#define IDD_PAGE_LOGIN                  133
#define IDD_PAGE_CONFIG                 134
#define IDD_PAGE_OTP                    135
#define IDB_PNG_LOGO                    136
#define IDD_PAGE_MAIN                   136
#define IDB_PNG_BTN_CLOSE               137
#define IDD_PAGE_PORT                   137
#define IDB_PNG_BTN_MIN                 138
#define IDB_PNG_BTN_CLOSE_H             140
#define IDB_PNG_BTN_MIN_H               142
#define IDD_DLG_TIMEOUT                 142
#define IDB_PNG_PANEL_LOGIN             143
#define IDB_PNG_EDT_SEL                 144
#define IDD_DLG_ALERT                   144
#define IDB_PNG_EDT_UNSEL               145
#define IDB_PNG_ICON_IP                 146
#define IDB_PNG_ICON_MAIL               147
#define IDB_PNG_ICON_MID                148
#define IDB_PNG_ICON_PWD                149
#define IDB_PNG_CHECK                   150
#define IDB_PNG_UNCHECK                 151
#define IDB_PNG_BTN_FULL                152
#define IDB_PNG_BTN_FULL_H              153
#define IDB_PNG_PANEL_CONFIG            154
#define IDB_PNG_BTN_HALF_B              155
#define IDB_PNG_BTN_HALF_BH             156
#define IDB_PNG_BTN_HALF_R              157
#define IDB_PNG_BTN_HALF_RH             158
#define IDB_PNG_PANEL_OTP               159
#define IDB_PNG_PIN_FILL_SEL            160
#define IDB_PNG_PIN_FILL_UNSEL          161
#define IDB_PNG_PIN_SEL                 162
#define IDB_PNG_PIN_UNSEL               163
#define IDB_PNG_ICON_CONFIG             164
#define IDB_PNG_ICON_EYE                165
#define IDB_PNG_TITLE                   166
#define IDB_PNG_STC_CONNECTED           167
#define IDB_PNG_PANEL_MAIN              168
#define IDB_PNG_BTN_ICON_DOWN           169
#define IDB_PNG_BTN_ICON_DOWN_H         170
#define IDB_PNG_BTN_ICON_POLICY         171
#define IDB_PNG_BTN_ICON_POLICY_H       172
#define IDB_PNG_BTN_ICON_REFRESH        173
#define IDB_PNG_BTN_ICON_REFRESH_H      174
#define IDB_PNG_BTN_ICON_START          175
#define IDB_PNG_BTN_ICON_START_H        176
#define IDB_PNG_BTN_ICON_STOP           177
#define IDB_PNG_BTN_ICON_STOP_H         178
#define IDB_PNG_LIST_ROW1               179
#define IDB_PNG_LIST_ROW2               180
#define IDB_PNG_LIST_ROW_SEL            181
#define IDB_PNG_LIST_HEAD               182
#define IDB_PNG1                        183
#define IDB_PNG_PORT_TITLE              183
#define IDB_PNG_ICON_PORT               184
#define IDB_PNG_PGS_FILL                185
#define IDB_PNG_PGS_BACK                186
#define IDR_MENU1                       187
#define IDB_PNG_BTN_ICON_NEXT_H         188
#define IDB_PNG_BTN_ICON_NEXT           189
#define IDB_PNG_BTN_ICON_OK_H           190
#define IDB_PNG_BTN_ICON_OK             191
#define IDB_PNG_BTN_ICON_SKIP_H         192
#define IDB_PNG_BTN_ICON_SKIP           193
#define IDB_PNG_STEP1                   194
#define IDB_PNG_STEP2                   195
#define IDB_PNG10                       196
#define IDB_PNG_STEP3                   196
#define IDB_PNG_BG_TRIAL                197
#define IDB_PNG_TRIAL_LOGIN             198
#define IDB_PNG_TRIAL_MAIN              199
#define IDB_PNG_TRIAL_SETTING           200
#define IDD_KLAUNCHER_TRIAL_DIALOG      201
#define IDB_PNG_ICON_DANGER             202
#define IDD_PAGE_OTP1                   202
#define IDD_PAGE_ABOUT_US               202
#define IDB_PNG_ICON_ERROR              203
#define IDB_PNG_ICON_WARNING            204
#define IDB_PNG_BTN_SMALL_D             205
#define IDB_PNG_BTN_SMALL_BLUE          206
#define IDB_PNG_BTN_SMALL_BLUE_H        207
#define IDB_PNG_BTN_SMALL_RED           208
#define IDB_PNG_BTN_SMALL_RED_H         210
#define IDB_PNG_BG_ALERT                211
#define IDB_PNG_STC_DISCONNECT          212
#define IDB_PNG_NET_STATUS_BG           214
#define IDB_PNG_COMBO_ACTIVE            215
#define IDB_PNG_COMBO_FIRST             216
#define IDB_PNG_COMBO_FIRST_H           217
#define IDB_PNG_COMBO_LAST              218
#define IDB_PNG_COMBO_LAST_H            219
#define IDB_PNG_COMBO_MIDDLE            220
#define IDB_PNG_COMBO_MIDDLE_H          221
#define IDB_PNG_NORMAL                  222
#define IDB_PNG_COMBO_NORMAL            222
#define IDB_PNG_BTN_BACK                224
#define IDB_PNG_ABOUT_US_BG             225
#define IDB_PNG_BTN_ICON_PAUSE          226
#define IDB_PNG_BTN_ICON_PAUSE_H        227
#define IDB_PNG2                        228
#define IDB_PNG_LIST_SCROLL             228
#define IDB_PNG_MENU                    229
#define IDB_PNG_MENU_H                  230
#define IDC_STC_LOGO                    1000
#define IDC_BTN_MIN                     1002
#define IDC_STC_TITLE                   1002
#define IDC_STC_TITLE2                  1003
#define IDC_STC_TITLE3                  1004
#define IDC_STC_PANEL                   1005
#define IDC_EDT_MID                     1006
#define IDC_STC_PERCENT                 1006
#define IDC_EDT_EMAIL                   1007
#define IDC_STC_TITLE4                  1007
#define IDC_STC_DOWN_NAME               1007
#define IDC_EDT_PWD                     1008
#define IDC_EDT_IP                      1009
#define IDC_CHK_REMEMBER                1010
#define IDC_BTN_LOGIN                   1012
#define IDC_BTN_SAVE                    1013
#define IDC_STC_MESSAGE                 1013
#define IDC_EDT_PORT                    1014
#define IDC_STC_MESSAGE2                1014
#define IDC_STC_MESSAGE1                1014
#define IDC_BTN_BACK                    1015
#define IDC_EDT_PIN1                    1016
#define IDC_EDT_PIN2                    1017
#define IDC_EDT_PIN3                    1018
#define IDC_EDT_PIN4                    1019
#define IDC_EDT_PIN5                    1020
#define IDC_EDT_PIN6                    1021
#define IDC_STC_RESEND                  1022
#define IDC_LST_GROUP                   1023
#define IDC_CMB_MENU                    1024
#define IDC_BUTTON1                     1025
#define IDC_BTN_REFRESH                 1025
#define IDC_BTN_OK                      1025
#define IDC_BTN_ICON                    1025
#define IDC_BTN_EXIT                    1025
#define IDC_BUTTON2                     1026
#define IDC_BTN_DOWNLOAD                1026
#define IDC_BTN_CLOSE                   1026
#define IDC_BUTTON3                     1027
#define IDC_BTN_START                   1027
#define IDC_BUTTON4                     1028
#define IDC_BTN_POLICY                  1028
#define IDC_STC_CONNECT                 1029
#define IDC_EDIT1                       1030
#define IDC_EDT_PATH                    1030
#define IDC_STC_INFO1                   1031
#define IDC_STC_INFO2                   1032
#define IDC_STC_INFO3                   1033
#define IDC_PGS_PERCENT                 1035
#define IDC_BTN_PAUSE                   1036
#define IDC_LST_PORT                    1036
#define IDC_DESCRIPTION                 1037
#define IDC_STC_SPEED                   1037
#define IDC_BTN_SKIP                    1038
#define IDC_STC_SPEED2                  1038
#define IDC_STC_RATE                    1038
#define IDC_BTN_NEXT                    1039
#define IDC_STATIC_NET_BG               1039
#define IDC_TRIAL_IMAGE                 1040
#define IDC_BTN_COMBO                   1040
#define IDC_BTN_TRIAL_IMG               1041
#define IDC_STATIC_LOGO                 1041
#define IDC_BTN_RADIO                   1042
#define IDC_STAATIC_ICON                1042
#define IDC_STATIC_BG                   1042
#define IDC_BTN_FINISH                  1043
#define IDC_STATIC_DESCRIPTION          1043
#define IDC_STC_POPUP                   1044
#define IDC_BUTTON5                     1045
#define ID_TRAY_OPEN                    32771
#define ID_MENU_EXIT                    32772
#define ID_TRAY_EXIT                    32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        231
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
